spring:
  mvc:
    async:
      request-timeout: 30s
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
server:
  port: 18089

## Mybatis
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_UUID
  configuration:
    cache-enabled: false
    ## 打印Sql日志
    ##log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/**.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

## Swagger
swagger:
  enable: true
  title: API查看器
  description:
  version: 1.0
  contact:
    name: tongtech
    url: a.b.c.d
    mail: a@b.c.d

## Framework
tsf:
  sm3:
    salt: 1234567890
  ##异步线程池
  async:
    executor:
      thread:
        core_pool_size: 5
        max_pool_size: 5
        queue_capacity: 999
        name:
          prefix: tong-async-
  request:
    ##不需要进行request封装的URI
    ignore: /**/druid/*
  ## 预留，后续跨域
  basePath: http://127.0.0.1:${server.port}

## Log Path
logging:
  file:
    path: logs/

## File Path
file:
  path: file/


## Auth Filter
auth:
  sign:
    ignoreGet: true
    timeGap: 3600000
    key: 123456